language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script: 
  - npm run clean:chrome
  - npm run clean:firefox
  - npm run build:chrome
  - npm run build:firefox
  - npm run pack:chrome
  - npm run pack:firefox